spring:
  application:
    name: pll-elasticsearch
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
  data:
    elasticsearch:
      cluster-name: pll-elasticsearch
      cluster-nodes: 127.0.0.1:9200
server:
  port: 8001

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pll.elasticsearch.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback-spring.xml
  level:
    com.pll.elasticsearch.dao: debug
